apiVersion: v1
kind: Pod
metadata:
  name: noe4j-pod
  labels:
    app: noe4j

spec:
  containers:
    - name: avib-db
      image: olbapd/avib-neo4j:avib-db
      volumeMounts:
        - mountPath: "/var/lib/neo4j/data"
          name: "data"
        - mountPath: "/var/lib/neo4j/logs"
          name: "logs"
        - mountPath: "/var/lib/neo4j/import"
          name: "import"
        - mountPath: "/var/lib/neo4j/plugins"
          name: "plugins"
      ports: 
        - containerPort: 7687
          name: bolt
        - containerPort: 7474
          name: http

restartPolicy: Always 