# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CI

on:
  push:
    paths:
      - './docker/server-docker/**'
    branches: [ master, development ]
  pull_request:
    paths:
      - './docker/server-docker/**'
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache node modules
      uses: actions/cache@v2.1.2
      working-directory: ./docker/server-docker
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.npm
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
            ${{ runner.os }}-node-     
   
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      working-directory: ./docker/server-docker
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm update
    - run: npm ci
    - run: npm run build --aot --if-present  
